"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { Maximize2, Pause, Play, Volume2, VolumeX } from "lucide-react";
import { cn } from "@/lib/utils";

/**
 * The landing page's centrepiece: an actual lesson this product generated —
 * board, imagery, narration and burned-in captions — not a scripted promo.
 *
 * It autoplays muted (the only kind of autoplay browsers allow) and loops, so
 * the page shows the output moving before anyone clicks anything. Sound is one
 * tap away rather than sprung on the visitor.
 */

const SRC = "/demo/lesson-demo.mp4";
const POSTER = "/demo/lesson-demo-poster.jpg";

function formatTime(seconds: number): string {
  if (!Number.isFinite(seconds)) return "0:00";
  const m = Math.floor(seconds / 60);
  const s = Math.floor(seconds % 60);
  return `${m}:${s.toString().padStart(2, "0")}`;
}

export function LessonVideo({ className }: { className?: string }) {
  const videoRef = useRef<HTMLVideoElement>(null);
  const [playing, setPlaying] = useState(true);
  const [muted, setMuted] = useState(true);
  const [progress, setProgress] = useState(0);
  const [current, setCurrent] = useState(0);
  const [duration, setDuration] = useState(0);

  /**
   * Autoplay is a nice-to-have, not a requirement: if the browser or the user's
   * reduced-motion setting blocks it, the poster stands in and the play button
   * still works.
   *
   * The explicit `muted = true` and `load()` are both load-bearing. React sets
   * `muted` as a property after the element is created, so the browser can make
   * its autoplay decision against an unmuted element and refuse; and calling
   * play() during mount — before resource selection has settled, twice over
   * under StrictMode's double-invoked effects — leaves the element stalled at
   * readyState 0 with the poster showing. Kicking off the load ourselves makes
   * the sequence deterministic.
   */
  useEffect(() => {
    const video = videoRef.current;
    if (!video) return;
    // defaultMuted, not just muted: load() below resets `muted` to whatever the
    // muted CONTENT ATTRIBUTE says, and React does not emit that attribute in
    // server-rendered markup. Setting only `.muted` here means load() clears it
    // and the lesson autoplays out loud at full volume.
    video.defaultMuted = true;
    video.muted = true;
    if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) {
      setPlaying(false);
      return;
    }
    video.load();
    video.play().catch(() => setPlaying(false));
  }, []);

  const togglePlay = useCallback(() => {
    const video = videoRef.current;
    if (!video) return;
    if (video.paused) {
      void video.play().catch(() => undefined);
      setPlaying(true);
    } else {
      video.pause();
      setPlaying(false);
    }
  }, []);

  const toggleMute = useCallback(() => {
    const video = videoRef.current;
    if (!video) return;
    video.muted = !video.muted;
    setMuted(video.muted);
    // Unmuting a paused video should start it — otherwise the control appears
    // to do nothing.
    if (!video.muted && video.paused) {
      void video.play().catch(() => undefined);
      setPlaying(true);
    }
  }, []);

  const seek = useCallback((event: React.MouseEvent<HTMLDivElement>) => {
    const video = videoRef.current;
    if (!video || !video.duration) return;
    const bounds = event.currentTarget.getBoundingClientRect();
    const ratio = (event.clientX - bounds.left) / bounds.width;
    video.currentTime = Math.min(Math.max(0, ratio), 1) * video.duration;
  }, []);

  return (
    <figure className={cn("group relative", className)}>
      {/* soft brand halo behind the frame */}
      <div
        aria-hidden
        className="pointer-events-none absolute -inset-x-6 -bottom-8 -top-4 rounded-[3rem] bg-gradient-to-tr from-primary/15 via-secondary/10 to-accent/15 blur-3xl"
      />

      <div className="relative overflow-hidden rounded-[1.5rem] border border-border bg-card shadow-float sm:rounded-[2rem]">
        {/* chrome */}
        <div className="flex items-center gap-2 border-b border-border bg-elevated px-4 py-2.5">
          <span className="h-2.5 w-2.5 rounded-full bg-rose-300" />
          <span className="h-2.5 w-2.5 rounded-full bg-amber-300" />
          <span className="h-2.5 w-2.5 rounded-full bg-emerald-300" />
          <span className="mx-auto hidden text-[11px] font-medium text-muted-foreground sm:block">
            Introduction to Photosynthesis · generated by SMART AI
          </span>
        </div>

        <div className="relative bg-[#0B1120]">
          <video
            ref={videoRef}
            src={SRC}
            poster={POSTER}
            loop
            playsInline
            preload="auto"
            className="block aspect-video w-full"
            onClick={togglePlay}
            onLoadedMetadata={(event) => setDuration(event.currentTarget.duration)}
            // If the first play() lost the race with resource selection, take
            // the next chance the element gives us.
            onCanPlay={(event) => {
              if (playing && event.currentTarget.paused) {
                event.currentTarget.play().catch(() => setPlaying(false));
              }
            }}
            onTimeUpdate={(event) => {
              const video = event.currentTarget;
              setCurrent(video.currentTime);
              if (video.duration) setProgress((video.currentTime / video.duration) * 100);
            }}
          />

          {/* big play affordance when paused */}
          {!playing && (
            <button
              type="button"
              onClick={togglePlay}
              aria-label="Play the demo lesson"
              className="absolute inset-0 flex items-center justify-center bg-slate-950/35 transition-colors hover:bg-slate-950/25"
            >
              <span className="flex h-16 w-16 items-center justify-center rounded-full bg-white/95 shadow-lift transition-transform hover:scale-105">
                <Play className="ml-0.5 h-6 w-6 fill-slate-900 text-slate-900" />
              </span>
            </button>
          )}

          {/* controls — always present on touch, revealed on hover for pointers */}
          <div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-slate-950/85 to-transparent px-4 pb-3 pt-10 opacity-100 transition-opacity duration-200 md:opacity-0 md:group-hover:opacity-100">
            <div
              role="presentation"
              onClick={seek}
              className="mb-2.5 h-1.5 cursor-pointer rounded-full bg-white/25"
            >
              <div
                className="h-full rounded-full bg-brand-gradient"
                style={{ width: `${progress}%` }}
              />
            </div>
            <div className="flex items-center gap-3 text-white">
              <button type="button" onClick={togglePlay} aria-label={playing ? "Pause" : "Play"}>
                {playing ? <Pause className="h-4 w-4" /> : <Play className="h-4 w-4" />}
              </button>
              <button
                type="button"
                onClick={toggleMute}
                aria-label={muted ? "Unmute narration" : "Mute narration"}
                className="flex items-center gap-1.5 text-xs font-medium"
              >
                {muted ? <VolumeX className="h-4 w-4" /> : <Volume2 className="h-4 w-4" />}
                {muted && <span className="hidden sm:inline">Hear the narration</span>}
              </button>
              <span className="ml-auto font-mono text-[11px] tabular-nums text-white/80">
                {formatTime(current)} / {formatTime(duration)}
              </span>
              <button
                type="button"
                onClick={() => videoRef.current?.requestFullscreen?.()}
                aria-label="Full screen"
                className="hidden sm:block"
              >
                <Maximize2 className="h-3.5 w-3.5" />
              </button>
            </div>
          </div>
        </div>
      </div>

      <figcaption className="mt-4 text-center text-sm text-muted-foreground">
        A real lesson, start to finish — slides, narration and captions, generated from one topic.
      </figcaption>
    </figure>
  );
}
