import { Schema, model, Document, Types } from "mongoose";
import { LESSON_LANGUAGES, type LessonLanguage } from "../config/languages";
import type { LearnerTraits } from "./LearningProfile";

export type AssetStatus = "pending" | "processing" | "ready" | "failed";

export type DiagramType = "flow" | "cycle" | "compare" | "list" | "none";

export interface SlideBoard {
  keyTerms: string[];
  /** Short written explanation lines the presenter adds under the terms. */
  notes: string[];
  diagram?: {
    type: DiagramType;
    nodes: string[];
  };
  /**
   * When each board item gets written, aligned to the narration. Built by
   * boardTimeline.service from the script + word boundaries; absent on lessons
   * generated before the timeline existed, which fall back to even reveals.
   */
  timeline?: BoardTimeline;
}

export type BoardEventKind = "term" | "note" | "node";

export interface BoardEvent {
  kind: BoardEventKind;
  index: number;
  /** Seconds into the slide's narration. */
  at: number;
  until: number;
  matched: boolean;
}

export interface BoardTimeline {
  events: BoardEvent[];
  /** Narration length the event times are relative to — the player rescales to actual. */
  durationSec: number;
  source: "spoken" | "estimated";
}

/** One spoken word and when it is said, from the voice's boundary events. */
export interface WordTiming {
  word: string;
  start: number;
  end: number;
}

/**
 * The written matter a student copies into a notebook.
 *
 * The slide bullets and the narration are what the learner *watches*; this is
 * what they are left holding afterwards — the explanation in full sentences,
 * the definitions they are expected to reproduce, the formula, one example
 * worked end to end, and a problem to try. Generated by a second AI pass
 * (studyNotes.service) rather than by the main lesson prompt, because asking
 * for all of it in one call blows the free-tier per-minute token budget.
 */
export interface Definition {
  term: string;
  meaning: string;
}

export interface WorkedExample {
  problem: string;
  /** The method, one step per line — a student should be able to follow it without the teacher. */
  steps: string[];
}

export interface PracticeProblem {
  question: string;
  answer: string;
}

export interface SlideStudyNotes {
  /** Full-sentence explanation, deeper than the bullets — meant to be copied down. */
  explanation: string;
  definitions: Definition[];
  /** Formulas, rules, numbers and orderings worth memorising. */
  keyFacts: string[];
  example?: WorkedExample;
  practice?: PracticeProblem;
  /** The error learners actually make on this concept. */
  commonMistake?: string;
}

export type DetailLevel = "quick" | "standard" | "detailed";

export interface GenerationOptions {
  /** Target lesson length in minutes; omitted = derived from the profile. */
  durationMin?: number;
  detailLevel?: DetailLevel;
  /** Generate captions (CC track + SRT) and burn them into the MP4. */
  subtitles?: boolean;
  /** Language the lesson is narrated in. */
  language?: LessonLanguage;
  /** Language written on the board and slides; unset = same as narration. */
  boardLanguage?: LessonLanguage;
}

export interface SlideContent {
  index: number;
  title: string;
  points: string[];
  imagePrompt: string;
  script: string;
  board?: SlideBoard;
  /** Notebook matter for the deck/handout; absent until the PPT stage writes it. */
  studyNotes?: SlideStudyNotes;
  imagePath?: string;
  imageCredit?: string;
  renderedImagePath?: string;
  /** Rendered final board frame for this slide (video). */
  boardImagePath?: string;
  audioPath?: string;
  audioDurationSec?: number;
  /**
   * Real per-word boundaries from the neural voice. Kept so the timeline can be
   * rebuilt later (e.g. after a board edit) without re-synthesising the audio.
   */
  wordTimings?: WordTiming[];
}

export interface QuizQuestion {
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
}

export interface PresentationDocument extends Document<Types.ObjectId> {
  userId: Types.ObjectId;
  topic: string;
  focus?: string;
  title: string;
  subject: string;
  summary: string;
  slides: SlideContent[];
  quiz: QuizQuestion[];
  profileSnapshot: LearnerTraits;
  generationOptions?: GenerationOptions;
  status: {
    content: AssetStatus;
    ppt: AssetStatus;
    audio: AssetStatus;
    video: AssetStatus;
  };
  error?: string;
  pptPath?: string;
  pdfPath?: string;
  fullAudioPath?: string;
  videoPath?: string;
  videoDurationSec?: number;
  /** When the current background video render started — used to detect stalled jobs. */
  videoJobStartedAt?: Date;
  /** True when a lip-synced talking-head presenter was composited into the video. */
  hasAvatar?: boolean;
  srtPath?: string;
  vttPath?: string;
  createdAt: Date;
  updatedAt: Date;
}

const generationOptionsSchema = new Schema<GenerationOptions>(
  {
    durationMin: { type: Number },
    detailLevel: { type: String, enum: ["quick", "standard", "detailed"] },
    subtitles: { type: Boolean },
    language: { type: String, enum: LESSON_LANGUAGES },
    boardLanguage: { type: String, enum: LESSON_LANGUAGES },
  },
  { _id: false }
);

const diagramSchema = new Schema<NonNullable<SlideBoard["diagram"]>>(
  {
    type: { type: String, enum: ["flow", "cycle", "compare", "list", "none"], required: true },
    nodes: { type: [String], default: [] },
  },
  { _id: false }
);

const boardEventSchema = new Schema<BoardEvent>(
  {
    kind: { type: String, enum: ["term", "note", "node"], required: true },
    index: { type: Number, required: true },
    at: { type: Number, required: true },
    until: { type: Number, required: true },
    matched: { type: Boolean, default: false },
  },
  { _id: false }
);

const boardTimelineSchema = new Schema<BoardTimeline>(
  {
    events: { type: [boardEventSchema], default: [] },
    durationSec: { type: Number, default: 0 },
    source: { type: String, enum: ["spoken", "estimated"], default: "estimated" },
  },
  { _id: false }
);

const boardSchema = new Schema<SlideBoard>(
  {
    keyTerms: { type: [String], default: [] },
    notes: { type: [String], default: [] },
    diagram: { type: diagramSchema, default: undefined },
    timeline: { type: boardTimelineSchema, default: undefined },
  },
  { _id: false }
);

const definitionSchema = new Schema<Definition>(
  {
    term: { type: String, required: true },
    meaning: { type: String, default: "" },
  },
  { _id: false }
);

const workedExampleSchema = new Schema<WorkedExample>(
  {
    problem: { type: String, required: true },
    steps: { type: [String], default: [] },
  },
  { _id: false }
);

const practiceProblemSchema = new Schema<PracticeProblem>(
  {
    question: { type: String, required: true },
    answer: { type: String, default: "" },
  },
  { _id: false }
);

const studyNotesSchema = new Schema<SlideStudyNotes>(
  {
    explanation: { type: String, default: "" },
    definitions: { type: [definitionSchema], default: [] },
    keyFacts: { type: [String], default: [] },
    example: { type: workedExampleSchema, default: undefined },
    practice: { type: practiceProblemSchema, default: undefined },
    commonMistake: { type: String },
  },
  { _id: false }
);

const wordTimingSchema = new Schema<WordTiming>(
  {
    word: { type: String, required: true },
    start: { type: Number, required: true },
    end: { type: Number, required: true },
  },
  { _id: false }
);

const slideSchema = new Schema<SlideContent>(
  {
    index: { type: Number, required: true },
    title: { type: String, required: true },
    points: { type: [String], default: [] },
    imagePrompt: { type: String, default: "" },
    script: { type: String, default: "" },
    board: { type: boardSchema, default: undefined },
    studyNotes: { type: studyNotesSchema, default: undefined },
    imagePath: { type: String },
    imageCredit: { type: String },
    renderedImagePath: { type: String },
    boardImagePath: { type: String },
    audioPath: { type: String },
    audioDurationSec: { type: Number },
    wordTimings: { type: [wordTimingSchema], default: undefined },
  },
  { _id: false }
);

const quizSchema = new Schema<QuizQuestion>(
  {
    question: { type: String, required: true },
    options: { type: [String], required: true },
    correctIndex: { type: Number, required: true },
    explanation: { type: String, default: "" },
  },
  { _id: false }
);

const statusField = { type: String, enum: ["pending", "processing", "ready", "failed"], default: "pending" };

const presentationSchema = new Schema<PresentationDocument>(
  {
    userId: { type: Schema.Types.ObjectId, ref: "User", required: true, index: true },
    topic: { type: String, required: true, trim: true },
    focus: { type: String, trim: true },
    title: { type: String, default: "" },
    subject: { type: String, default: "General" },
    summary: { type: String, default: "" },
    slides: { type: [slideSchema], default: [] },
    quiz: { type: [quizSchema], default: [] },
    profileSnapshot: { type: Schema.Types.Mixed, required: true },
    generationOptions: { type: generationOptionsSchema, default: undefined },
    status: {
      content: statusField,
      ppt: statusField,
      audio: statusField,
      video: statusField,
    },
    error: { type: String },
    pptPath: { type: String },
    pdfPath: { type: String },
    fullAudioPath: { type: String },
    videoPath: { type: String },
    videoDurationSec: { type: Number },
    videoJobStartedAt: { type: Date },
    hasAvatar: { type: Boolean, default: false },
    srtPath: { type: String },
    vttPath: { type: String },
  },
  { timestamps: true }
);

presentationSchema.index({ userId: 1, createdAt: -1 });

export const Presentation = model<PresentationDocument>("Presentation", presentationSchema);
